apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-content
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-content
        configMap:
          name: app2-html
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app2-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>App2</title>
        <style>
            body { 
                background: linear-gradient(135deg, #11998e 0%, #38ef7d 100%);
                color: white; 
                font-family: Arial, sans-serif; 
                text-align: center; 
                padding-top: 100px; 
            }
            h1 { font-size: 3em; margin-bottom: 20px; }
            p { font-size: 1.5em; }
        </style>
    </head>
    <body>
        <h1>Application 2</h1>
        <p>Welcome to App2 - Nginx Server</p>
        <p>Host: app2.com</p>
    </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: app2-service
spec:
  selector:
    app: app2
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80