Vagrant.configure("2") do |config|
  config.vm.define "ktroudeS" do |server|
    server.vm.box = "ubuntu/jammy64"
    server.vm.hostname = "ktroudeS"
    server.vm.network "private_network", ip: "192.168.56.110"
    
    server.vm.provider "virtualbox" do |vb|
      vb.name = "ktroudeS"
      vb.memory = 2048
      vb.cpus = 2
    end
    
    server.vm.provision "shell", path: "./init_server.sh"
  end
end
