
$scriptS = <<-SCRIPT

    set -e

    sudo apt-get update --fix-missing
    sudo apt-get install -y curl

# definition env pour k3s
    export K3S_KUBECONFIG_MODE="644"
    export INSTALL_K3S_EXEC="server --node-ip=192.168.56.110"
# dl k3s
    curl -sfL https://get.k3s.io | sh -

# attendre l' attribution du token
    TOKEN="/var/lib/rancher/k3s/server/node-token"
    while [ ! -f "$TOKEN" ]; do
        sleep 2
    done

# stocker le token dans le dossier partage de vagrant
    sudo cp $TOKEN /vagrant/token

# Copie du fichier kubeconfig pour l'accès depuis l'hôte
    KUBECONFIG="/etc/rancher/k3s/k3s.yaml"
    sudo cp $KUBECONFIG /vagrant/k3s.yaml
    sudo chmod 644 /vagrant/k3s.yaml

echo "alias k='kubectl'" >> /home/vagrant/.bashrc

SCRIPT


$scriptSW = <<-SCRIPT

    set -e

    sudo apt-get update --fix-missing
    sudo apt-get install -y curl

# definir l' adresse du server et le chemin vers le token
    SERVER_IP="192.168.56.110"
    TOKEN_FILE="/vagrant/token"

# attendre que le server genere le token
    while [ ! -f "$TOKEN_FILE" ]; do
        sleep 2
    done

# recuperer le token dans le fichier partage de vagrant
    NODE_TOKEN=$(cat $TOKEN_FILE)

# Précision du mode agent de l'internal IP du cluster
    export INSTALL_K3S_EXEC="agent --node-ip=192.168.56.111"
    curl -sfL https://get.k3s.io | K3S_URL="https://${SERVER_IP}:6443" K3S_TOKEN="${NODE_TOKEN}"  sh -

    echo "alias k='kubectl'" >> /home/vagrant/.bashrc

SCRIPT


Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/jammy64"
    # config.vm.network "private_network", type: "dhcp"
  
    config.vm.define "ktroudeS" do |server|
      server.vm.hostname = "ktroudeS"
      server.vm.network "private_network", type: "static", ip: "192.168.56.110"
      server.vm.provider "virtualbox" do |vb|
        vb.cpus = 2
        vb.memory = "1024"
      end
      server.vm.provision "shell", inline: $scriptS
    end
  
    config.vm.define "ktroudeSW" do |worker|
      worker.vm.hostname = "ktroudeSW"
      worker.vm.network "private_network", type: "static", ip: "192.168.56.111"
      worker.vm.provider "virtualbox" do |vb|
        vb.cpus = 2
        vb.memory = "1024"
      end
      worker.vm.provision "shell", inline: $scriptSW
    end

end
