Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/jammy64"
  
    config.vm.define "ktroudeS" do |server|
      server.vm.hostname = "ktroudeS"
      server.vm.network "private_network", type: "static", ip: "192.168.56.110"
      server.vm.provider "virtualbox" do |vb|
        vb.cpus = 2
        vb.memory = "2048"
      end
      server.vm.provision "shell", path: "./init_server.sh"
    end
  
    config.vm.define "ktroudeSW" do |worker|
      worker.vm.hostname = "ktroudeSW"
      worker.vm.network "private_network", type: "static", ip: "192.168.56.111"
      worker.vm.provider "virtualbox" do |vb|
        vb.cpus = 2
        vb.memory = "2048"
      end
      worker.vm.provision "shell", path: "./init_worker.sh"
    end

end
